FROM python:3.10-alpine

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install pytest httpx

CMD ["pytest", "tests/", "-v"]