# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'post_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12post_service.proto\x12\x04post\"j\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"\x99\x01\n\x0cPostResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\x12\x12\n\nis_private\x18\x07 \x01(\x08\x12\x0c\n\x04tags\x18\x08 \x03(\t\"\x1c\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\t\"e\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"\x1f\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65letePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"C\n\x10ListPostsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"e\n\x11ListPostsResponse\x12!\n\x05posts\x18\x01 \x03(\x0b\x32\x12.post.PostResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x10\n\x08per_page\x18\x04 \x01(\x05\x32\xb7\x02\n\x0bPostService\x12\x39\n\nCreatePost\x12\x17.post.CreatePostRequest\x1a\x12.post.PostResponse\x12\x33\n\x07GetPost\x12\x14.post.GetPostRequest\x1a\x12.post.PostResponse\x12\x39\n\nUpdatePost\x12\x17.post.UpdatePostRequest\x1a\x12.post.PostResponse\x12?\n\nDeletePost\x12\x17.post.DeletePostRequest\x1a\x18.post.DeletePostResponse\x12<\n\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=28
  _globals['_CREATEPOSTREQUEST']._serialized_end=134
  _globals['_POSTRESPONSE']._serialized_start=137
  _globals['_POSTRESPONSE']._serialized_end=290
  _globals['_GETPOSTREQUEST']._serialized_start=292
  _globals['_GETPOSTREQUEST']._serialized_end=320
  _globals['_UPDATEPOSTREQUEST']._serialized_start=322
  _globals['_UPDATEPOSTREQUEST']._serialized_end=423
  _globals['_DELETEPOSTREQUEST']._serialized_start=425
  _globals['_DELETEPOSTREQUEST']._serialized_end=456
  _globals['_DELETEPOSTRESPONSE']._serialized_start=458
  _globals['_DELETEPOSTRESPONSE']._serialized_end=495
  _globals['_LISTPOSTSREQUEST']._serialized_start=497
  _globals['_LISTPOSTSREQUEST']._serialized_end=564
  _globals['_LISTPOSTSRESPONSE']._serialized_start=566
  _globals['_LISTPOSTSRESPONSE']._serialized_end=667
  _globals['_POSTSERVICE']._serialized_start=670
  _globals['_POSTSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
